image: registry.gitlab.com/shrugal/wow-packager:latest

stages:
  - build
  - deploy

before_script:
  - WOWI_ID=$(case $CI_COMMIT_TAG in *next*|*ptr*) echo $WOWI_ID_NEXT;; ""|*debug*|*alpha*|*beta*) echo $WOWI_ID_TEST;; *) echo $WOWI_ID;; esac)

.releases: &releases
  only:
    - /^\d[\d\.]*(-(debug|alpha|beta)\d+)?$/

build:
  stage: build
  only:
    - tags
    - web
  script:
    - release.sh -d
  artifacts:
    paths:
      - .release/TestFlight/
      - .release/*.zip

curseforge:
  <<: *releases
  stage: deploy
  environment:
    name: CurseForge
    url: https://www.curseforge.com/wow/addons/TestFlight
  script:
    - release.sh -ocelzWAHG

wowinterface:
  <<: *releases
  stage: deploy
  environment:
    name: WoWInterface
    url: https://www.wowinterface.com/downloads/info26514-TestFlight.html
  script:
    - release.sh -ocelzLAHG

wago:
  <<: *releases
  stage: deploy
  environment:
    name: Wago
    url: https://addons.wago.io/addons/testflight
  script:
    - release.sh -ocelzLWHG

github:
  <<: *releases
  stage: deploy
  environment:
    name: GitHub
    url: https://github.com/shrugal/TestFlight/releases
  script:
    - release.sh -ocelzLWAG

gitlab:
  <<: *releases
  stage: deploy
  environment:
    name: GitLab
    url: https://gitlab.com/shrugal/TestFlight/releases
  script:
    - release.sh -ocelzLAWH
